### ISSUE TITLE
Question about running in windows

### ISSUE THREAD

**Issue by uzibuxing** [meyerls/colmap-wrapper#8]
Thank you for your work!
Is this pypl can not run in windows? When I pip install, some error occured.

**Comment by meyerls** [comment]
Sorry for the late response. I have not tried to get this repo work on windows. What errors have you encountered during your installation?

**Comment by uzibuxing** [comment]
> Sorry for the late response. I have not tried to get this repo work on windows. What errors have you encountered during your installation?

Thank you, sir. I think I have installed successfully. Sorry  I forget to close this issues.

**Comment by meyerls** [comment]
No Problem, feel free to suggest some improvements
